# -*- coding: utf-8 -*-
"""spp_cbam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/180hHOLUk2Jsy3JyJ_yXwngDHsRHtvI4H
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class ChannelAttention(nn.Module):
    def __init__(self, in_channels, reduction=16):
        super(ChannelAttention, self).__init__()
        self.mlp = nn.Sequential(
            nn.Linear(in_channels, in_channels // reduction, bias=False),
            nn.ReLU(),
            nn.Linear(in_channels // reduction, in_channels, bias=False)
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_pool = F.adaptive_avg_pool2d(x, 1).view(x.size(0), x.size(1))
        max_pool = F.adaptive_max_pool2d(x, 1).view(x.size(0), x.size(1))
        avg_out = self.mlp(avg_pool)
        max_out = self.mlp(max_pool)
        scale = self.sigmoid(avg_out + max_out).unsqueeze(2).unsqueeze(3)
        return x * scale

class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super(SpatialAttention, self).__init__()
        padding = (kernel_size - 1) // 2
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=padding, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # x: [B, C, H, W]
        avg_pool = torch.mean(x, dim=1, keepdim=True)
        max_pool, _ = torch.max(x, dim=1, keepdim=True)
        concat = torch.cat([avg_pool, max_pool], dim=1)
        scale = self.sigmoid(self.conv(concat))
        return x * scale

class CBAM(nn.Module):
    def __init__(self, in_channels, reduction=16, kernel_size=7):
        super(CBAM, self).__init__()
        self.channel_attention = ChannelAttention(in_channels, reduction)
        self.spatial_attention = SpatialAttention(kernel_size)

    def forward(self, x):
        x = self.channel_attention(x)
        x = self.spatial_attention(x)
        return x

class SPP(nn.Module):
    def __init__(self, in_channels, pool_sizes=[1, 2, 4]):
        """
        Applies spatial pyramid pooling:
          - For each pool size, it uses adaptive average pooling to a fixed output size,
          - Then upsamples back to the input spatial size.
        """
        super(SPP, self).__init__()
        self.pool_sizes = pool_sizes
        # We'll concatenate the original feature map with pooled versions,
        # so the output channel count will be in_channels * (len(pool_sizes)+1)
        self.conv = nn.Conv2d(in_channels * (len(pool_sizes) + 1), in_channels, kernel_size=1)

    def forward(self, x):
        B, C, H, W = x.shape
        outputs = [x]
        for size in self.pool_sizes:
            pooled = F.adaptive_avg_pool2d(x, output_size=(size, size))
            upsampled = F.interpolate(pooled, size=(H, W), mode='bilinear', align_corners=False)
            outputs.append(upsampled)
        out = torch.cat(outputs, dim=1)
        out = self.conv(out)
        return out

class SPP_CBAM(nn.Module):
    def __init__(self, in_channels, out_channels, pool_sizes=[1, 2, 4]):
        # Combines SPP and CBAM.
        super(SPP_CBAM, self).__init__()
        self.spp = SPP(in_channels, pool_sizes)
        # Project to out_channels if needed.
        if in_channels != out_channels:
            self.project = nn.Conv2d(in_channels, out_channels, kernel_size=1)
        else:
            self.project = nn.Identity()
        self.cbam = CBAM(out_channels)

    def forward(self, x):
        out = self.spp(x)
        out = self.project(out)
        out = self.cbam(out)
        return out