# -*- coding: utf-8 -*-
"""spp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCvl9113wILsBgzGZht8KIGDww0xRzu0
"""

import torch
import torch.nn as nn

class SPPModule(nn.Module):
    def __init__(self, in_channels, out_channels, pool_sizes=[1, 3, 5, 7]):
        super(SPPModule, self).__init__()
        self.convs = nn.ModuleList([
            nn.Conv2d(in_channels, out_channels, kernel_size=ks, padding=ks // 2)
            for ks in pool_sizes
        ])

    def forward(self, x):
        features = [conv(x) for conv in self.convs]
        return torch.cat(features, dim=1)